// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QroratTeb.Data;

#nullable disable

namespace QroratTeb.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260922092849_AddFamilyMembersFields")]
    partial class AddFamilyMembersFields
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("QroratTeb.Entities.Family", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Area")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BuildingNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Floor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Landmark")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PrimaryContactName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WhatsAppNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Families");
                });

            modelBuilder.Entity("QroratTeb.Entities.Servant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Committee")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Servants");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Committee = "المنطقة الأولى",
                            Name = "خادم تجريبي",
                            Phone = "01000000000"
                        });
                });

            modelBuilder.Entity("QroratTeb.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ServantId")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ServantId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            PasswordHash = "admin123",
                            Role = "Admin",
                            Username = "admin"
                        });
                });

            modelBuilder.Entity("QroratTeb.Entities.Visit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CaregiverAvailable")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConfessorName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("FamilyId")
                        .HasColumnType("int");

                    b.Property<string>("HasConfessor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HealthCategory")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HealthcareAssistanceTypes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IsBedridden")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsResolved")
                        .HasColumnType("bit");

                    b.Property<string>("OriginatingCommittee")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PriestName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PriorityFlag")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ServantId")
                        .HasColumnType("int");

                    b.Property<string>("SocialSupportCategories")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SpiritualServiceType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SpiritualUrgency")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SupportLevel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("VisitDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("WasPriestPresent")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("FamilyId");

                    b.HasIndex("ServantId");

                    b.ToTable("Visits");
                });

            modelBuilder.Entity("QroratTeb.Entities.VisitIndividual", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ChildName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DateOfBirth")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EducationalStage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeceased")
                        .HasColumnType("bit");

                    b.Property<bool>("IsHeadOfFamily")
                        .HasColumnType("bit");

                    b.Property<string>("NonAttendanceReason")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Relation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SchoolCollegeName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("VisitId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("VisitId");

                    b.ToTable("VisitIndividuals");
                });

            modelBuilder.Entity("QroratTeb.Entities.VisitNeed", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("NeedCategory")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("VisitId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("VisitId");

                    b.ToTable("VisitNeeds");
                });

            modelBuilder.Entity("QroratTeb.Entities.User", b =>
                {
                    b.HasOne("QroratTeb.Entities.Servant", "Servant")
                        .WithMany()
                        .HasForeignKey("ServantId");

                    b.Navigation("Servant");
                });

            modelBuilder.Entity("QroratTeb.Entities.Visit", b =>
                {
                    b.HasOne("QroratTeb.Entities.Family", "Family")
                        .WithMany("Visits")
                        .HasForeignKey("FamilyId");

                    b.HasOne("QroratTeb.Entities.Servant", "Servant")
                        .WithMany()
                        .HasForeignKey("ServantId");

                    b.Navigation("Family");

                    b.Navigation("Servant");
                });

            modelBuilder.Entity("QroratTeb.Entities.VisitIndividual", b =>
                {
                    b.HasOne("QroratTeb.Entities.Visit", "Visit")
                        .WithMany("Individuals")
                        .HasForeignKey("VisitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Visit");
                });

            modelBuilder.Entity("QroratTeb.Entities.VisitNeed", b =>
                {
                    b.HasOne("QroratTeb.Entities.Visit", "Visit")
                        .WithMany("Needs")
                        .HasForeignKey("VisitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Visit");
                });

            modelBuilder.Entity("QroratTeb.Entities.Family", b =>
                {
                    b.Navigation("Visits");
                });

            modelBuilder.Entity("QroratTeb.Entities.Visit", b =>
                {
                    b.Navigation("Individuals");

                    b.Navigation("Needs");
                });
#pragma warning restore 612, 618
        }
    }
}
